version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: tokped-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tokped-net

  backend:
    build: .
    container_name: tokped-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=tokopedia_db
      - JWT_SECRET=tokopedia_production_secret_key_vps_2026
      - FRONTEND_URL=*
      - GIN_MODE=release
    depends_on:
      - mongodb
    networks:
      - tokped-net

volumes:
  mongo_data:
    driver: local

networks:
  tokped-net:
    driver: bridge